import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  overviewSidebar: [
    'rtg',
    'automated-testing'
  ],
    
  frameworkSidebar: [
    'rtg-framework/components/core-extensibile-description',
    {
      type: 'category',
      label: 'Core Components',
      link: {
        type: 'generated-index',
        description: 'This section presents the core components within the RTG framework.'
      },
      items: ['rtg-framework/parser/parser',
              'rtg-framework/datatype/parameters',
              'rtg-framework/datatype/operation',
              'rtg-framework/odg/odg',
              'rtg-framework/interaction-processor/interaction-processor',
      ]
    },
    {
      type: 'category',
      label: 'Extensible Components',
      link: {
        type: 'generated-index',
        description: 'This section presents the extensible components within the RTG framework.'
      },
      items: ['rtg-framework/operation-sorter/operation-sorter',
              'rtg-framework/pvp/pvp',
              'rtg-framework/mutator/mutator',
              'rtg-framework/oracle/oracle',
              'rtg-framework/writer/writer',
              'rtg-framework/strategy/strategy',
      ]
    },
  ],

  strategiesSidebar: [
    'rtg-tool/strategy/introduction',
    'rtg-tool/strategy/nominal-error-strategy',
    'rtg-tool/strategy/mass-assignment-strategy',
    'rtg-tool/strategy/nlp-strategy',
  ]

};

export default sidebars;
